class CountryCityData {
  static const Map<String, List<String>> countriesWithCities = {
    'Afghanistan': [
      'Kabul',
      'Kandahar',
      'Herat',
      'Mazar-i-Sharif',
      'Jalalabad',
    ],
    'Albania': ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier'],
    'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'],
    'Argentina': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata'],
    'Armenia': ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Hrazdan'],
    'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'],
    'Austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
    'Azerbaijan': ['Baku', 'Ganja', 'Sumgayit', 'Mingachevir', 'Quba'],
    'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'A\'ali'],
    'Bangladesh': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet'],
    'Belarus': ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno'],
    'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège'],
    'Bosnia and Herzegovina': [
      'Sarajevo',
      'Banja Luka',
      'Tuzla',
      'Zenica',
      'Mostar',
    ],
    'Brazil': [
      'São Paulo',
      'Rio de Janeiro',
      'Brasília',
      'Salvador',
      'Fortaleza',
    ],
    'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'],
    'Cambodia': [
      'Phnom Penh',
      'Siem Reap',
      'Battambang',
      'Sihanoukville',
      'Poipet',
    ],
    'Canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton'],
    'Chile': [
      'Santiago',
      'Valparaíso',
      'Concepción',
      'La Serena',
      'Antofagasta',
    ],
    'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu'],
    'Colombia': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'],
    'Croatia': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'],
    'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec'],
    'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
    'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El-Kheima', 'Port Said'],
    'Estonia': ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'],
    'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'],
    'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice'],
    'Georgia': ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi', 'Zugdidi'],
    'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt'],
    'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Ashaiman'],
    'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'],
    'Hungary': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs'],
    'Iceland': [
      'Reykjavik',
      'Kópavogur',
      'Hafnarfjörður',
      'Akureyri',
      'Garðabær',
    ],
    'India': ['New Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai'],
    'Indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Bekasi', 'Medan'],
    'Iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz'],
    'Iraq': ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf'],
    'Ireland': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'],
    'Israel': [
      'Jerusalem',
      'Tel Aviv',
      'Haifa',
      'Rishon LeZion',
      'Petah Tikva',
    ],
    'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo'],
    'Japan': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo'],
    'Jordan': ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Wadi as-Sir'],
    'Kazakhstan': ['Almaty', 'Nur-Sultan', 'Shymkent', 'Aktobe', 'Taraz'],
    'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
    'Kuwait': [
      'Kuwait City',
      'Al Ahmadi',
      'Hawalli',
      'As Salimiyah',
      'Sabah as Salim',
    ],
    'Kyrgyzstan': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok'],
    'Latvia': ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala'],
    'Lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Nabatieh'],
    'Libya': ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Al Bayda'],
    'Lithuania': ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
    'Luxembourg': [
      'Luxembourg City',
      'Esch-sur-Alzette',
      'Dudelange',
      'Schifflange',
      'Bettembourg',
    ],
    'Malaysia': [
      'Kuala Lumpur',
      'George Town',
      'Ipoh',
      'Shah Alam',
      'Petaling Jaya',
    ],
    'Maldives': [
      'Malé',
      'Addu City',
      'Fuvahmulah',
      'Kulhudhuffushi',
      'Thinadhoo',
    ],
    'Mexico': ['Mexico City', 'Ecatepec', 'Guadalajara', 'Puebla', 'Tijuana'],
    'Morocco': ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Agadir'],
    'Nepal': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar'],
    'Netherlands': [
      'Amsterdam',
      'Rotterdam',
      'The Hague',
      'Utrecht',
      'Eindhoven',
    ],
    'New Zealand': [
      'Auckland',
      'Wellington',
      'Christchurch',
      'Hamilton',
      'Tauranga',
    ],
    'Norway': ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen'],
    'Oman': ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar'],
    'Pakistan': [
      'Islamabad',
      'Karachi',
      'Lahore',
      'Faisalabad',
      'Rawalpindi',
      'Multan',
      'Hyderabad',
      'Gujranwala',
      'Peshawar',
      'Quetta',
      'Sialkot',
      'Bahawalpur',
      'Sargodha',
      'Sukkur',
      'Larkana',
      'Chiniot',
      'Jhang',
      'Sheikhupura',
      'Rahim Yar Khan',
      'Gujrat',
      'Sahiwal',
      'Wah Cantonment',
      'Mardan',
      'Kasur',
      'Okara',
      'Mingora',
      'Nawabshah',
      'Chiniot',
      'Kotri',
      'Khanpur',
      'Hafizabad',
      'Sadiqabad',
      'Mirpur Khas',
      'Turbat',
      'Jacobabad',
    ],
    'Philippines': [
      'Quezon City',
      'Manila',
      'Caloocan',
      'Davao City',
      'Cebu City',
    ],
    'Poland': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań'],
    'Portugal': ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora', 'Braga'],
    'Qatar': ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah', 'Al Khor'],
    'Romania': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța'],
    'Russia': [
      'Moscow',
      'Saint Petersburg',
      'Novosibirsk',
      'Yekaterinburg',
      'Kazan',
    ],
    'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam'],
    'Serbia': ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'],
    'Singapore': ['Singapore'],
    'Slovakia': ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica'],
    'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje'],
    'South Africa': [
      'Cape Town',
      'Johannesburg',
      'Durban',
      'Pretoria',
      'Port Elizabeth',
    ],
    'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon'],
    'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza'],
    'Sri Lanka': [
      'Colombo',
      'Dehiwala-Mount Lavinia',
      'Moratuwa',
      'Negombo',
      'Kandy',
    ],
    'Sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'],
    'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern'],
    'Syria': ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'],
    'Taiwan': ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Taoyuan'],
    'Tajikistan': [
      'Dushanbe',
      'Khujand',
      'Kulob',
      'Qurghonteppa',
      'Istaravshan',
    ],
    'Thailand': ['Bangkok', 'Nonthaburi', 'Pak Kret', 'Hat Yai', 'Chiang Mai'],
    'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana'],
    'Turkmenistan': [
      'Ashgabat',
      'Turkmenbashi',
      'Türkmenabat',
      'Mary',
      'Balkanabat',
    ],
    'Ukraine': ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk'],
    'United Arab Emirates': [
      'Dubai',
      'Abu Dhabi',
      'Sharjah',
      'Al Ain',
      'Ajman',
    ],
    'United Kingdom': [
      'London',
      'Birmingham',
      'Manchester',
      'Glasgow',
      'Liverpool',
    ],
    'United States': [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
    ],
    'Uzbekistan': ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Nukus'],
    'Vietnam': ['Ho Chi Minh City', 'Hanoi', 'Haiphong', 'Da Nang', 'Bien Hoa'],
    'Yemen': ['Sanaa', 'Aden', 'Taiz', 'Al Hudaydah', 'Mukalla'],
  };

  static List<String> get countries =>
      countriesWithCities.keys.toList()..sort();

  static List<String> getCitiesForCountry(String country) {
    return countriesWithCities[country] ?? [];
  }

  static List<String> searchCountries(String query) {
    if (query.isEmpty) return countries;

    return countries
        .where((country) => country.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }

  static List<String> searchCities(String country, String query) {
    final cities = getCitiesForCountry(country);
    if (query.isEmpty) return cities;

    return cities
        .where((city) => city.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }
}
